Added build and deploy workflow for EXM frontend
EndavaCollab/bvdapprenticeship2024-expenses-manager pull request #10
Opened 2024-08-20 13:08 UTC by mirunaenc

Added build and deploy workflow for EXM frontend. Configured steps for SSH, Nginx installation, and deployment of the Angular app.

2024-08-20 13:29 UTC, en-vasiliuralucaelena requested changes
Pipeline-ul trebui sa se afle intr-un fisier numit .github/workflows/build_deploy_exm_fe.yml care este la acelasi nivel cu expenses-manager-frontend

2024-08-20 13:52 UTC, en-vasiliuralucaelena requested changes

2024-08-20 13:52 UTC, en-vasiliuralucaelena commented on .github/workflows/build_deploy_exm_fe.yml
> +      run: echo "::set-output name=vm_ip::$(terraform output -raw public_ip)"
Nu cred ca o sa mearga cu terraform output aici, in primul rand nu rulezi terraform in pipeline-ul asta si in al doilea rand terraformul e in alt repo, deci runnerul care va rula pipeline-ul nici nu o sa aiba access la terraformul nostru. Ai putea sa incerci o comanda de azure cli care sa ia ip-ul de la vm. Va trebui facut Azure login si aici ca sa mearga cu az cli

2024-08-20 13:52 UTC, en-vasiliuralucaelena commented on .github/workflows/build_deploy_exm_fe.yml
> +        ssh -o StrictHostKeyChecking=no $TF_VAR_admin_username@${{ steps.get-vm-ip.outputs.vm_ip }} << 'EOF'
TF_VAR_admin_username probabil va fi numit doar admin_username, prefixul de TF_VAR se pune pentru variabilele care sunt folosite in terraform, nu este nevoie aici

2024-08-20 13:52 UTC, en-vasiliuralucaelena commented on expenses-manager-frontend/.github/workflows/build_deploy_exm_fe.yml
Acest fisier care inca se afla in expenses-manager-frontend/.github/workflows/build_deploy_exm_fe.yml trebuie sters

2024-08-20 19:58 UTC, vlsts requested changes

2024-08-20 19:58 UTC, vlsts commented on .github/workflows/build_deploy_exm_fe.yml
> +        node-version: '14'
Desi ar trebui sa mearga (vezi [aici](https://github.com/angular/angular-cli/blob/ec1008d27d0f38afcc450d1ed9ea47f21402dd5c/package.json#L44)) nu vad de ce nu am putea da bump la versiune la ultimul LTS, 20.16.0.

2024-08-20 19:58 UTC, vlsts commented on .github/workflows/build_deploy_exm_fe.yml
> +      run: npm run build --prod
`--prod` e deprecated (vezi [aici](https://v13.angular.io/cli/build)). Poti folosi `--configuration production` sau chiar nimic avand in vedere ca by default configul selectat e cel de production. (vezi [aici](https://github.com/EndavaCollab/bvdapprenticeship2024-expenses-manager/blob/901f8364584ee1418b69b057186b267c109d2c10/expenses-manager-frontend/src/main/frontend/angular.json#L66))

2024-08-20 19:58 UTC, vlsts commented on .github/workflows/build_deploy_exm_fe.yml
> +        ssh -o StrictHostKeyChecking=no $admin_username@${{ steps.get-vm-ip.outputs.vm_ip }} << 'EOF'
asta nu o sa iti mearga pentru ca nu folosesti cheia pentru autentificare si autentificarea cu parola e oprita pe servere (cred si sper) (vezi `-i` [aici](https://man.openbsd.org/ssh#i)). pe langa asta din cate stiu eu nu ai metoda sigura prin care sa pui cheia privata direct in comanda, va trebui facuta o variabila pentru cheie si sa pui continutul ei intr-un fisier temporar pe care sa il folosesti in comanda.

2024-08-20 19:58 UTC, vlsts commented on .github/workflows/build_deploy_exm_fe.yml
> +        scp -o StrictHostKeyChecking=no -r dist/* $admin_username@${{ steps.get-vm-ip.outputs.vm_ip }}:/var/www/html/
si aici ai nevoie de cheia privata.

2024-08-20 19:58 UTC, vlsts commented on .github/workflows/build_deploy_exm_fe.yml
> +        scp -o StrictHostKeyChecking=no -r dist/* $admin_username@${{ steps.get-vm-ip.outputs.vm_ip }}:/var/www/html/
`dist/*` nu o sa functioneze pentru ca nu exista. poti seta CWD in `expenses-manager-frontend/src/main/frontend` sau sa inlocuiesti cu `expenses-manager-frontend/src/main/frontend/dist` in comanda.

2024-08-29 11:04 UTC, en-nader-said requested changes

2024-08-29 11:04 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_fe.yml
> +    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
Probabil nu vrem sa facem deploy la pull request, deci merge scoasa asta cu pull_request de aici, dar sa facem deploy cu workflow dispatch sau push in main branch

2024-08-29 11:04 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_fe.yml
> +        EOF
Astea doua am putea sa le combinam ca sa nu facem ssh de 2 ori

2024-08-29 11:15 UTC, en-vasiliuralucaelena requested changes

2024-08-29 11:15 UTC, en-vasiliuralucaelena commented on .github/workflows/build_deploy_exm_fe.yml
> +    - name: Upload build artifacts
Nu vrem sa facem upload la artifact daca se face build, poti pune is aici acelasi if ca la build-ul de deploy

2024-08-30 12:16 UTC, en-nader-said submitted a review, later dismissed

2024-08-30 12:16 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_fe.yml
> +        export BE_BASE_URL=http://backend-url-here
Vreau sa adaugi asta la comanda de mvn clean install, cauta in documentatie la maven la cum poti da variabila la comanda, nu o sa te ajute exportul aici

2024-08-30 12:16 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_fe.yml
> +        export BE_BASE_URL=http://backend-url-here
Si o sa vrem la backend-url-here sa punem ip-ul de la backend si port-ul cred, deci http://ip:8080

2024-08-30 12:47 UTC, en-vasiliuralucaelena approved these changes

2024-08-30 12:59 UTC, vlsts approved these changes

2024-08-30 13:11 UTC, merged