EXM-9 Create CRUD operations for expenses
EndavaCollab/bvdapprenticeship2024-expenses-manager pull request #11
Opened 2024-08-20 16:26 UTC by thatBeatrice

- Created the necessary classes to perform CRUD operations on expenses using Controller-Service-Repository architecture.

2024-08-21 06:42 UTC, en-dragos-dordea requested changes

2024-08-21 06:42 UTC, en-dragos-dordea commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<Expense> createExpense(@RequestParam LocalDateTime date, @RequestParam Category category,
All the expense fields should come as a request body - check `@RequestBody` annotation. The object we receive should be a new DTO object.

2024-08-21 06:42 UTC, en-dragos-dordea commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/controller/ExpenseController.java
> +    public ResponseEntity<Expense> updateExpense(@PathVariable int id, @RequestParam LocalDateTime date,
Same for update - lets try using `@RequestBody`

2024-08-22 08:28 UTC, en-florin-arhip commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        this.expenseMapper = ExpenseMapper.INSTANCE;
For mapper I would prefer initialization at declaration time. Just a preference 😄

2024-08-22 08:28 UTC, en-florin-arhip commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        for (Expense expense : expenses) {
A suggestion, you can try to see how it would be done with Stream API?

2024-08-22 12:06 UTC, en-florin-arhip commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/service/impl/ExpenseServiceImpl.java
> +        return expenses.stream().map(expenseMapper::expenseToExpenseDto).toList();
I suggest formatting the code to make it easier to read it. Here are some examples https://medium.com/javarevisited/10-java-stream-tips-must-read-2063a84af3be

2024-08-26 08:23 UTC, en-florin-arhip approved these changes

2024-08-26 16:04 UTC, en-dragos-dordea approved these changes

2024-08-26 16:09 UTC, merged