[7-DevOps] Pipeline Deploy Backend
EndavaCollab/bvdapprenticeship2024-expenses-manager pull request #13
Opened 2024-08-27 07:28 UTC by mirunaenc

Created pipeline to build and deploy the backend Java application. Includes setup for Java and Maven, installation of necessary Java services, and deployment steps to VM.

2024-08-29 11:06 UTC, en-nader-said requested changes

2024-08-29 11:06 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_be.yml
> +    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
Nu cred ca vrem sa facem deploy la pull request, doar build, deci merge scos event pull_request de aici, si vrem sa facem deploy doar la push in main sau cu workflow dispatch

2024-08-29 11:16 UTC, en-vasiliuralucaelena requested changes

2024-08-29 11:16 UTC, en-vasiliuralucaelena commented on .github/workflows/build_deploy_exm_be.yml
> +    - name: Upload build artifacts
Acelasi comment ca si in celalalt pipeline

2024-08-30 12:19 UTC, en-nader-said requested changes

2024-08-30 12:19 UTC, en-nader-said commented on .github/workflows/build_deploy_exm_be.yml
> +      run: mvn clean install
Aici trebuie adaugate variabilele pentru database ca si extra argumente la comanda

2024-08-30 12:23 UTC, en-nader-said approved these changes

2024-08-30 12:48 UTC, en-vasiliuralucaelena approved these changes

2024-08-30 12:57 UTC, merged