EXM-2 Create database initial structure
EndavaCollab/bvdapprenticeship2024-expenses-manager pull request #2
Opened 2024-08-05 13:59 UTC by thatBeatrice

2024-08-06 15:35 UTC, ProtVlad requested changes
Codul este ok, dar am câteva recomandări de făcut:
1. poți să elimini numele clasei din denumirea câmpurilor (de exemplu pentru clasa Category să ai câmpurile id, description, color)
2. când atribui denumirea atributelor din baza de date, poți elimina denumirea tabelei
3. în clasa Currency, câmpul code trebuie să aibă nullable=false, este un câmp obligatoriu
4. ar fi mai bine să numești clasa User în loc de Users (toate clasele sunt la singular, mai puțin User)
5. în clasa User, câmpul id ar putea fi de tip int

2024-08-07 07:42 UTC, en-dragos-dordea commented
la punctul:
"4. ar fi mai bine să numești clasa User în loc de Users (toate clasele sunt la singular, mai puțin User)"
- cred ca in MySql cuvantul `User` e rezervat si nu il poti folosi, de aceea am sugerat in schema sa fie `Users`

2024-08-07 07:49 UTC, en-dragos-dordea commented on expenses-manager-backend/src/main/java/com/endava/expensesmanager/entity/Expense.java
> +    private Timestamp expenseDate;
Hai sa incercam sa folosim `LocalDate` sau `LocalDateTime` in java - vezi cum se poate serializa/deserializa data/timestamp din sql in obiecte de java

2024-08-07 07:51 UTC, en-dragos-dordea commented
@thatBeatrice cum se creeaza structura bazei de date? se fac tabelele in functie de clasele din java?

2024-08-07 07:59 UTC, thatBeatrice commented
Pentru punctul: 
"2. când atribui denumirea atributelor din baza de date, poți elimina denumirea tabelei"

Am gasit cuvinte precum **description** si **code** ca fiind rezervate in MySQL si de asta am inclus si denumirea tabelei. O solutie ar fi sa le inlocuiesc cu label si alt cuvant pentru codul valutei.

2024-08-07 08:00 UTC, thatBeatrice commented
> @thatBeatrice cum se creeaza structura bazei de date? se fac tabelele in functie de clasele din java?

Da, tabelele se fac in functie de clasele din Java.

2024-08-07 16:13 UTC, ProtVlad approved these changes

2024-08-08 06:46 UTC, en-dragos-dordea approved these changes

2024-08-08 06:46 UTC, merged